<?php
$this->headTitle('Panels');

$this->mainMenu()->setActiveItemId('portal');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Manage Panels' => $this->url('panels'),
    'Add Panels' => $this->url('panels', ['action' => 'add'])
]);
$form->setAttributes(array(
    'enctype' => 'multipart/form-data'
));
?>
<h1>Manage Panels</h1>
<?php
echo $this->partial('portal/portal/partials/form.phtml', array('form' => $form));
?>